#!/usr/bin/env python3
"""Generate compact M5GFX VLW fonts and embeddable C++ arrays.

The VLW layout matches the Processing/TFT_eSPI format consumed by M5GFX.  The
script intentionally emits only printable ASCII because the dashboard never
renders arbitrary user content.
"""

from __future__ import annotations

import argparse
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


PRINTABLE_ASCII = range(0x21, 0x7F)


def generate_vlw(font_path: Path, size: int) -> bytes:
    font = ImageFont.truetype(str(font_path), size=size)
    ascent, descent = font.getmetrics()
    glyph_headers: list[bytes] = []
    glyph_bitmaps: list[bytes] = []

    for codepoint in PRINTABLE_ASCII:
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(0, right - left)
        height = max(0, bottom - top)
        advance = max(1, round(font.getlength(character)))
        top_extent = -top

        bitmap = Image.new("L", (max(1, width), max(1, height)), 0)
        if width and height:
            draw = ImageDraw.Draw(bitmap)
            draw.text((-left, -top), character, font=font, fill=255, anchor="ls")
            glyph_bitmap = bitmap.crop((0, 0, width, height)).tobytes()
        else:
            glyph_bitmap = b""

        glyph_headers.append(
            struct.pack(
                ">7i",
                codepoint,
                height,
                width,
                advance,
                top_extent,
                left,
                0,
            )
        )
        glyph_bitmaps.append(glyph_bitmap)

    header = struct.pack(
        ">6i",
        len(glyph_headers),
        11,
        size,
        0,
        ascent,
        descent,
    )
    return header + b"".join(glyph_headers) + b"".join(glyph_bitmaps)


def array_text(name: str, payload: bytes) -> str:
    rows = []
    for offset in range(0, len(payload), 16):
        chunk = payload[offset : offset + 16]
        rows.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return (
        f"static constexpr std::uint8_t {name}[] = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--small-size", type=int, default=18)
    parser.add_argument("--large-size", type=int, default=46)
    args = parser.parse_args()

    small = generate_vlw(args.font, args.small_size)
    large = generate_vlw(args.font, args.large_size)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "// Generated by scripts/generate_vlw_font.py. Do not edit manually.\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace dashboard {\nnamespace font_data {\n\n"
        + array_text("kSpaceMono18Vlw", small)
        + "\n"
        + array_text("kSpaceMono46Vlw", large)
        + "\n}  // namespace font_data\n}  // namespace dashboard\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
